import os
from stringcolor import cs
import time
def clear_console():
    # Je nach Betriebssystem den passenden Befehl zum Löschen der Konsole verwenden
    os.system('cls' if os.name == 'nt' else 'clear')
string = """
# WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
# WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
# WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
# WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
# WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
# WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
# WWWWWWWWWWWWWWKOkkOOkOOKNNKOkkkkOkOXNKOkkOOOOOKNWWWWKOkkkkO0XWWKOkkkkkkkkOXX0OkOkOOkOKWWX0OkkkOOKWWWWWWWWWWWWWW
# WWWWWWWWWWWWWXd::::::::ckOo:::::::lO0l::::::::o0WWNOl::::::cxNXd:::::::::ckkc:::::::ckKxc::::::ckNWWWWWWWWWWWWW
# WWWWWWWWWWWWWKo:::ldl:::oOOdl:::cdOX0l:::odc::cOWW0o::colc::lOX0xxl:::cdxOKx:::cloookXOc:::clooxKWWWWWWWWWWWWWW
# WWWWWWWWWWWWWKo:::lxo:::oXWXd:::oKWW0l:::loc::ckXXd:::okxl:::oKWWNx:::l0WWNx::::cccoKW0c::::cclokNWWWWWWWWWWWWW
# WWWWWWWWWWWWWKo::::::::o0WWXd:::oKWW0l::::c::::ckOl::::::::::lOWWNx:::l0WWNk:::clookXWNOdolcc:::l0WWWWWWWWWWWWW
# WWWWWWWWWWWWWKo:::lkOO0NWXkoc:::coxK0l::cx0kl:::xkc::coddl:::cOWWNx:::l0WWNk:::cloodd0Kkoollc:::l0WWWWWWWWWWWWW
# WWWWWWWWWWWWWXd::ckNWWWWWKo:::::::o00l::l0WKo::lkOl::oKWNOl::l0WWNxc:coKWWNkc:::::::lOOl::::::cd0NWWWWWWWWWWWWW
# WWWWWWWWWWWWWNK00KNWWWWWWNK000000KXWNK00XWWNK00KNNK00XWWWNK0KXWWWWX00KXWWWWXK0000000KNNK00000KXNWWWWWWWWWWWWWWW
# WWWWWWWWMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
# WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
# WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
# WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
"""

colorer = 1
counter = 0
color = ""
while(counter <=10000):
    if colorer == 1:
        color = "red"
    if colorer == 2:
        color = "blue"
    if colorer == 3:
        color = "white"
    if colorer == 4:
        color = "yellow"
    if colorer == 5:
        color = "green"
    if colorer == 6:
        color = "black"
    counter = counter +1
    if colorer >= 5:
        colorer = 1
    colorer = colorer +1
    print(cs(string,color))
    time.sleep(0.2)
    clear_console()