import time

def blink_text(text):
    for char in text:
        if char == ":":
            print("\033[31m" + char, end="", flush=True)  # Blinking red text
        else:
            print("\033[0m" + char, end="", flush=True)  # Steady black text
        time.sleep(0.001)  # Pause for 0.5 seconds
    print("\033[0m")  # Reset text color to default

text = """
# WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
# WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
# WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
# WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
# WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
# WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
# WWWWWWWWWWWWWWKOkkOOkOOKNNKOkkkkOkOXNKOkkOOOOOKNWWWWKOkkkkO0XWWKOkkkkkkkkOXX0OkOkOOkOKWWX0OkkkOOKWWWWWWWWWWWWWW
# WWWWWWWWWWWWWXd::::::::ckOo:::::::lO0l::::::::o0WWNOl::::::cxNXd:::::::::ckkc:::::::ckKxc::::::ckNWWWWWWWWWWWWW
# WWWWWWWWWWWWWKo:::ldl:::oOOdl:::cdOX0l:::odc::cOWW0o::colc::lOX0xxl:::cdxOKx:::cloookXOc:::clooxKWWWWWWWWWWWWWW
# WWWWWWWWWWWWWKo:::lxo:::oXWXd:::oKWW0l:::loc::ckXXd:::okxl:::oKWWNx:::l0WWNx::::cccoKW0c::::cclokNWWWWWWWWWWWWW
# WWWWWWWWWWWWWKo::::::::o0WWXd:::oKWW0l::::c::::ckOl::::::::::lOWWNx:::l0WWNk:::clookXWNOdolcc:::l0WWWWWWWWWWWWW
# WWWWWWWWWWWWWKo:::lkOO0NWXkoc:::coxK0l::cx0kl:::xkc::coddl:::cOWWNx:::l0WWNk:::cloodd0Kkoollc:::l0WWWWWWWWWWWWW
# WWWWWWWWWWWWWXd::ckNWWWWWKo:::::::o00l::l0WKo::lkOl::oKWNOl::l0WWNxc:coKWWNkc:::::::lOOl::::::cd0NWWWWWWWWWWWWW
# WWWWWWWWWWWWWNK00KNWWWWWWNK000000KXWNK00XWWNK00KNNK00XWWWNK0KXWWWWX00KXWWWWXK0000000KNNK00000KXNWWWWWWWWWWWWWWW
# WWWWWWWWMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
# WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
# WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
# WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
"""

blink_text(text)